name: Proponi una feature 💡
description: Suggerisci qualcosa di utile o interessante da sviluppare.
title: "[Feature] "
labels: [enhancement]
body:
  - type: textarea
    attributes:
      label: Di cosa si tratta?
      description: Spiega l’idea e perché pensi sia utile.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Note aggiuntive
      description: Qualsiasi altra informazione utile o esempio.
    validations:
      required: false
